--Tarea 1 Segundo Parcial Lleymi Cruz
------------------------------------
--Ejercicio 1
CREATE OR REPLACE TRIGGER TR_EMPLOYEES
BEFORE DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
IF INSTR(:OLD.JOB_ID,'CLERK', 1,1 )<> 0 THEN
RAISE_APPLICATION_ERROR(-20000, 'SU JOB_ID ES ' || :OLD.JOB_ID || ' POR TANTO NO PUEDE ELIMINARLO');
END IF;
END;
--PRUEBA
DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID=141;
-------------------------------------------------------------------------
/
--EJERCICIO 2
CREATE OR REPLACE TRIGGER TR_DEPARTMENTS
BEFORE INSERT ON DEPARTMENTS
FOR EACH ROW
BEGIN
 FOR i IN (SELECT*FROM DEPARTMENTS) LOOP 
    IF i.DEPARTMENT_ID=:NEW.DEPARTMENT_ID THEN
    RAISE_APPLICATION_ERROR(-20000, 'CÓDIGO REPETIDO');
    END IF;
    END LOOP;

IF :NEW.LOCATION_ID IS NULL THEN 
:NEW.LOCATION_ID:=1700;
END IF;

IF :NEW.MANAGER_ID IS NULL THEN 
:NEW.MANAGER_ID:=200;
END IF;
END;
--PRUEBAS
--CODIGO REPETIDO
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES(200, 'Viajes');
--CODIGO NUEVO
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES(290, 'Viajes');
------------------------------------------------------------------------------------------

--EJERCICIO 3
CREATE TABLE EMPLEADOS
 (
 CODIGO INT NOT NULL PRIMARY KEY,
 NOMBRE VARCHAR2(20),
 SALARIO DECIMAL(10,2)
 );

CREATE TABLE LOG_SALARIO
 (
 codigo INT,
 salario_anterior DECIMAL(10,2),
 salario_actual DECIMAL(10,2),
 fecha DATE,
 usuario VARCHAR2(20),
 operacion varchar2(20)
 );
CREATE SEQUENCE CODIGO
START WITH 1 
INCREMENT BY 1
NOCACHE;
--------------------
CREATE OR REPLACE TRIGGER TR_EMPLEADOS
BEFORE INSERT OR UPDATE OR DELETE ON EMPLEADOS 
FOR EACH ROW
BEGIN 
IF INSERTING THEN
INSERT INTO LOG_SALARIO VALUES(CODIGO.NEXTVAL, 1, :NEW.salario, SYSDATE, USER, 'Inserción');
END IF;
IF UPDATING ('SALARIO') THEN
INSERT INTO LOG_SALARIO VALUES(CODIGO.NEXTVAL, :OLD.salario, :NEW.salario, SYSDATE, USER, 'Actualización');
END IF;
IF DELETING THEN
INSERT INTO LOG_SALARIO VALUES(CODIGO.NEXTVAL, :OLD.SALARIO, 1, SYSDATE, USER, 'Eliminación');
END IF;
END;
--PRUEBAS
INSERT INTO EMPLEADOS VALUES(001, 'LLEYMI CRUZ', 25000);
UPDATE EMPLEADOS SET SALARIO=35000 WHERE CODIGO=001;
DELETE FROM EMPLEADOS WHERE CODIGO=001;
INSERT INTO EMPLEADOS VALUES(002, 'LIBERIO YAQUI', 50000);
UPDATE EMPLEADOS SET SALARIO=20000 WHERE CODIGO=002;